### ISSUE TITLE
Error on import DigiPyRo on Mac

### ISSUE THREAD

**Issue by spencerahill** [sam-may/DigiPyRo#10]
Using Python 2.7.12 via the Anaconda distribution on a Macbook Pro with OS X 10.11.6.

``` python
In [1]: import DigiPyRo
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/spencer/miniconda3/envs/py27/lib/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "/Users/spencer/Dropbox/py/DigiPyRo/DigiPyRo.py", line 341, in start
    width = int(vid.get(cv2.cv.CV_CAP_PROP_FRAME_WIDTH))
AttributeError: 'module' object has no attribute 'cv'
```

Importantly, I have not installed openCV via `brew` -- I only installed the python bindings via `pip install opencv-python`.  So maybe that's the issue?  When I find time to play around more, will update.

**Comment by sam-may** [comment]
I've been working on installing openCV via `pip install opencv-python` on a Macbook with Python 2.7 and OS X 10.10.5 (not my Macbook, which already has the brewed version of openCV) and have not been able to get it to run successfully. Specifically, I cannot `import cv2`, which is the openCV module that DigiPyRo needs.

According to this blog post:
http://www.pyimagesearch.com/2015/06/15/install-opencv-3-0-and-python-2-7-on-osx/
"As I’m sure you already know, OpenCV has never been an effortless library to install. It’s not like you can let `pip`  or `easy_install` to the heavy-lifting for you."

I'm inclined to think that the command `pip install opencv-python` does not install the full openCV package: installing via `pip install opencv-python` takes around 10 seconds while installing openCV via `brew install opencv` takes around 20 minutes. 

I'm also inclined to think that there may not be an easy way to install openCV with python, for the following reason. The installation process outlined in the blog post is similarly complex to mine, along with these others:
http://www.mobileway.net/2015/02/14/install-opencv-for-python-on-mac-os-x/
https://prateekvjoshi.com/2015/10/09/installing-opencv-3-with-python-on-mac-os-x/
It seems that someone would have discovered an easier way to install openCV with python by now if it were possible. So, this may make #14 a dead end.

**Comment by sam-may** [comment]
After reading a little more:
https://pypi.python.org/pypi/opencv-python

`opencv-python` is a wrapper package for openCV python bindings. Its current status for OSX/Linux is "failing". I think this explains why we have had trouble with it. 😆

**Comment by spencerahill** [comment]
**Edit: I may be wrong about this; see https://github.com/sam-may/DigiPyRo/issues/14#issuecomment-271327035 and discussion therein**

>opencv-python is a wrapper package for openCV python bindings.

Yes, you're correct.  I was being naive when I tried to use the python binding without installing the library itself!

Unless you're able to work on opencv itself and somehow improve its installation procedure, there's really not much to be done.  Any package, including digipyro, has dependencies, and those dependencies have to get installed somehow.  If it was a less important dependency, then you could try to swap it out with something easier to install.  But in the case of digipyro, opencv is clearly critical, so I think you just have to live with its install procedure.

The good thing about there being all of these prior blog posts about the opencv installation is that digipyro can just refer to them (ideally, it would be the official opencv documentation on installation, but their official documentation is quite the mess).  In fact, it's better to refer users elsewhere for this information, so that you don't have to maintain it yourself as opencv evolves and installation procedures inevitably change.

What that leaves is 1) making digipyro itself installable via a one-liner (`pip install digipyro`) *once its dependencies are installed* and 2) describing clearly in digipyro's documentation the installation procedure: each dependency and how to install them, with links to the external installation instructions as necessary.

**Comment by sam-may** [comment]
I've reproduced @spencerahill 's original error. I believe the problem is that I wrote DigiPyRo using openCV 2, while the version installed by `pip install opencv-python` is openCV 3 in which some of the modules have been renamed. So, I'll migrate DigiPyRo to openCV 3.

**Comment by spencerahill** [comment]
@sam-may nice, good to update to the latest opencv version anyways.

**Comment by sam-may** [comment]
No longer migrating to openCV 3, as `pip install opencv-python` installs an incomplete version of openCV 3 that does not have all of the video-related functions that DigiPyRo needs.
