### ISSUE TITLE
Simplify Installation Process

### ISSUE THREAD

**Issue by sam-may** [sam-may/DigiPyRo#14]
Ideally, we can achieve a one line installation process:

```pip install digipyro```

once the other Python packages used by `digipyro` have been installed (`cv2`,`numpy`,`scipy`, `TKinter`, `matplotlib`, `time`). The other specific aim is to get rid of the need for the user to manually link `python` with `opencv` (time consuming and technically involved process). Will investigate potential ways to do so (`pip install opencv-python` resulted in an error for @spencerahill -- perhaps we can determine why and adapt `digipyro` to work with this type of installation).

**Comment by spencerahill** [comment]
(Edited: see [comment below](https://github.com/sam-may/DigiPyRo/issues/14#issuecomment-271327035))
~~See https://github.com/sam-may/DigiPyRo/issues/10#issuecomment-271209794 for relevant discussion.  In short, there's little we can do about making opencv itself easy to install; we can only make digipyro easy to install once the user already has opencv installed.~~

**Comment by spencerahill** [comment]
Looks like I spoke to soon: https://github.com/skvark/opencv-python/issues/7#issuecomment-271221789
