### ISSUE TITLE
Migrate to openCV 3.2.0

### ISSUE THREAD

**Issue by sam-may** [sam-may/DigiPyRo#15]
Update all `.py` files to be consistent with openCV 3.2.0 module names and syntax.

**Comment by sam-may** [comment]
Looks like we have run into trouble. Using Python 2.7 and openCV 3.2.0, I receive the following error:

`error: /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window.cpp:565: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvNamedWindow`

according to the documentation for the Python bindings for openCV 3.2.0, https://pypi.python.org/pypi/opencv-python , video-related functionality is not supported for Mac OSX or Linux. The majority of openCV functions used in DigiPyRo are video-related, so this looks like a showstopper to me.

**Comment by spencerahill** [comment]
Shoot!  So in other words the full openCV install is required after all?
